/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.bonitasoft.engine.dsl.process

import com.winterbe.expekt.should
import org.bonitasoft.engine.bpm.bar.actorMapping.Actor
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

object ConfigurationTest : Spek({

    describe("A process configuration DSL") {


        it("should have actor mappings") {
            val configuration = configuration {
                actorMapping {
                    "validators" toGroup "/validators"
                    "requesters" to {
                        user("john")
                        membership("/requesters", "member")
                        role("member")
                    }
                }
            }

            val exported = configuration.export()

            exported.actorMapping!!.actors[0].name.should.equal("validators")
            exported.actorMapping!!.actors[0].groups.should.equal(setOf("/validators"))
            exported.actorMapping!!.actors[1].name.should.equal("requesters")
            exported.actorMapping!!.actors[1].memberships.should.equal(setOf(Actor.Membership("/requesters","member")))
            exported.actorMapping!!.actors[1].roles.should.equal(setOf("member"))
        }
        it("should have parameters") {
            val configuration = configuration {
                parameters {
                    "myParam1" to "maValue1"
                    "myParam2" to "maValue2"
                }
            }

            val exported = configuration.export()

            exported.parameters!!.should.equal(mapOf("myParam1" to "maValue1", "myParam2" to "maValue2"))
        }
    }
})
