/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.bonitasoft.engine.dsl.process

import com.winterbe.expekt.should
import org.bonitasoft.engine.dsl.process.DataType.Companion.string
import org.bonitasoft.engine.dsl.process.ExpressionDSLBuilder.ExpressionDSLBuilderObject.constant
import org.bonitasoft.engine.dsl.process.ExpressionDSLBuilder.ExpressionDSLBuilderObject.groovy
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

object ConnectorTest : Spek({

    describe("A task having a connector") {

        val process = process("MyProcess", "1.0") {

            initiator("john")
            data {
                text named "resourceName"
                text named "myOtherData"
            }
            automaticTask("taskWithOps") {
                connector{
                    email {
                        from(constant("no-reply@acme.com"))
                        to(constant("baptiste.mesta@gmail.com"))
                        subject(constant("rejected"))
                        message(constant("your request was rejected"))
                    }
                }
            }

        }
        val businessArchive = process.export()
        val processDefinition = businessArchive.processDefinition

        it("should have the right name and version") {
            val task = processDefinition.flowElementContainer.getActivity("taskWithOps")
            task.connectors.should.have.size(1)
            task.connectors[0].connectorId.should.equal("email")
            task.connectors[0].inputs.keys.sorted().should.equal(listOf("from","to","subject","message").sorted())
            businessArchive.getResource("connector/email.impl").should.be.not.`null`
        }
    }
})
